experimental-features = nix-command flakes
nix-path = nixpkgs=flake:nixpkgs
max-jobs = auto

extra-substituters = https://cache.nix.igor.kyiv.ua
extra-trusted-public-keys = main:P19l+SrizYl29qjYc8f3SFQBEs++8FrLS45iJt6iXKs=
